EMBED_MODEL: "openai:text-embedding-3-large"
CHAT_MODEL: "openai:gpt-4o"
DATA_PATH: "test_data/ICA2609_ExamplesKE(2).pdf"
CHROMA_PATH: "chroma_db"
LANGSMITH_TRACING: True
LANGSMITH_PROJECT: "pr-formal-replacement-44"
LANGSMITH_ENDPOINT: "https://api.smith.langchain.com"
TEMPERATURE: 0.2
