# Exported from Render on 2026-04-27T17:41:11Z
version: "1"
projects:
- name: Langchain-Chatbot
  environments:
  - name: Production
    services:
    - type: web
      name: Langchain-chatbot
      runtime: python
      repo: https://github.com/MMoyanoFontana/Langchain-chatbot
      plan: free
      envVars:
      - key: BACKEND_CORS_ORIGINS
        sync: false
      - key: GROQ_API_KEY
        sync: false
      - key: GEMINI_API_KEY
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: LANGSMITH_PROJECT
        sync: false
      - key: LANGSMITH_API_KEY
        sync: false
      - key: LANGSMITH_ENDPOINT
        sync: false
      - key: LANGSMITH_TRACING
        sync: false
      - key: PINECONE_INDEX_NAME
        sync: false
      - key: PINECONE_API_KEY
        sync: false
      - key: API_KEY_ENCRYPTION_KEY
        sync: false
      - key: AUTH_SECRET
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: AUTH_GOOGLE_CLIENT_ID
        sync: false
      - key: AUTH_GOOGLE_CLIENT_SECRET
        sync: false
      - key: AUTH_GITHUB_CLIENT_ID
        sync: false
      - key: AUTH_GITHUB_CLIENT_SECRET
        sync: false
      region: oregon
      buildCommand: uv sync
      startCommand: uv run fastapi run main.py
      autoDeployTrigger: commit
      rootDir: backend/
