import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter } from "next/font/google";
import { AppSidebar } from "@/components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { TooltipProvider } from "@/components/ui/tooltip";
import { ThemeProvider } from "@/components/theme-provider";
import type { SidebarUser } from "@/hooks/use-sidebar-user";
import "./globals.css";

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });
const BACKEND_URL = process.env.BACKEND_URL ?? "http://127.0.0.1:8000";
const DEFAULT_AVATAR_PATH = "/avatars/shadcn.jpg";

type CurrentUserResponse = {
  email?: string | null;
  full_name: string | null;
};

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const getInitialAppUser = async (): Promise<SidebarUser | null> => {
  const backendEndpoint = new URL("/users/dev/current", BACKEND_URL);

  try {
    const response = await fetch(backendEndpoint, {
      headers: { Accept: "application/json" },
      cache: "no-store",
    });

    if (!response.ok) {
      return null;
    }

    const payload = (await response.json()) as CurrentUserResponse;
    const email = payload.email?.trim() ?? "";
    if (!email) {
      return null;
    }

    return {
      name: payload.full_name?.trim() || email,
      email,
      avatar: DEFAULT_AVATAR_PATH,
    };
  } catch {
    return null;
  }
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialUser = await getInitialAppUser();

  return (
    <html lang="en" className={inter.variable} suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} h-svh overflow-hidden antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TooltipProvider>
            <SidebarProvider className="h-svh max-h-svh overflow-hidden">
              <AppSidebar initialUser={initialUser} />
              <div className="flex min-w-0 flex-1 flex-col overflow-hidden">
                <header className="flex h-12 shrink-0 items-center px-3">
                  <SidebarTrigger />
                </header>
                <div className="min-h-0 min-w-0 flex-1 overflow-hidden p-2">{children}</div>
              </div>
            </SidebarProvider>
          </TooltipProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
